### ISSUE TITLE
synopsis wrong

### ISSUE THREAD

**Issue by pjlsergeant** [Manwar/Data-Money#2]
the synopsis says:

`my $price = Data::Money->new(value => 1.2. code => 'USD');`

but this gives an error, as it needs a hashref instead

**Comment by manwar** [comment]
It gives error because of "." after "1,2". It needs to be replaced by ",".
thanks for raising the issue. @pjlsergeant

**Comment by manwar** [comment]
Data::Money v0.18 released.
https://metacpan.org/release/MANWAR/Data-Money-0.18

**Comment by pjlsergeant** [comment]
ah so it does! Anyway, glad you fixed it :-)
